/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppStudyRouteImport } from './routes/_authenticated/app.study'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated/app.settings'
import { Route as AuthenticatedAppReviewsRouteImport } from './routes/_authenticated/app.reviews'
import { Route as AuthenticatedAppPerformanceRouteImport } from './routes/_authenticated/app.performance'
import { Route as AuthenticatedAppPdfBatteriesRouteImport } from './routes/_authenticated/app.pdf-batteries'
import { Route as AuthenticatedAppImportanceRouteImport } from './routes/_authenticated/app.importance'
import { Route as AuthenticatedAppHoursRouteImport } from './routes/_authenticated/app.hours'
import { Route as AuthenticatedAppFlashcardsRouteImport } from './routes/_authenticated/app.flashcards'
import { Route as AuthenticatedAppErrorsRouteImport } from './routes/_authenticated/app.errors'
import { Route as AuthenticatedAppEditalRouteImport } from './routes/_authenticated/app.edital'
import { Route as AuthenticatedAppCycleRouteImport } from './routes/_authenticated/app.cycle'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppStudyRoute = AuthenticatedAppStudyRouteImport.update({
  id: '/app/study',
  path: '/app/study',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/app/settings',
    path: '/app/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppReviewsRoute = AuthenticatedAppReviewsRouteImport.update({
  id: '/app/reviews',
  path: '/app/reviews',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppPerformanceRoute =
  AuthenticatedAppPerformanceRouteImport.update({
    id: '/app/performance',
    path: '/app/performance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppPdfBatteriesRoute =
  AuthenticatedAppPdfBatteriesRouteImport.update({
    id: '/app/pdf-batteries',
    path: '/app/pdf-batteries',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppImportanceRoute =
  AuthenticatedAppImportanceRouteImport.update({
    id: '/app/importance',
    path: '/app/importance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppHoursRoute = AuthenticatedAppHoursRouteImport.update({
  id: '/app/hours',
  path: '/app/hours',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppFlashcardsRoute =
  AuthenticatedAppFlashcardsRouteImport.update({
    id: '/app/flashcards',
    path: '/app/flashcards',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppErrorsRoute = AuthenticatedAppErrorsRouteImport.update({
  id: '/app/errors',
  path: '/app/errors',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppEditalRoute = AuthenticatedAppEditalRouteImport.update({
  id: '/app/edital',
  path: '/app/edital',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppCycleRoute = AuthenticatedAppCycleRouteImport.update({
  id: '/app/cycle',
  path: '/app/cycle',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/cycle': typeof AuthenticatedAppCycleRoute
  '/app/edital': typeof AuthenticatedAppEditalRoute
  '/app/errors': typeof AuthenticatedAppErrorsRoute
  '/app/flashcards': typeof AuthenticatedAppFlashcardsRoute
  '/app/hours': typeof AuthenticatedAppHoursRoute
  '/app/importance': typeof AuthenticatedAppImportanceRoute
  '/app/pdf-batteries': typeof AuthenticatedAppPdfBatteriesRoute
  '/app/performance': typeof AuthenticatedAppPerformanceRoute
  '/app/reviews': typeof AuthenticatedAppReviewsRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/study': typeof AuthenticatedAppStudyRoute
  '/app/': typeof AuthenticatedAppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/cycle': typeof AuthenticatedAppCycleRoute
  '/app/edital': typeof AuthenticatedAppEditalRoute
  '/app/errors': typeof AuthenticatedAppErrorsRoute
  '/app/flashcards': typeof AuthenticatedAppFlashcardsRoute
  '/app/hours': typeof AuthenticatedAppHoursRoute
  '/app/importance': typeof AuthenticatedAppImportanceRoute
  '/app/pdf-batteries': typeof AuthenticatedAppPdfBatteriesRoute
  '/app/performance': typeof AuthenticatedAppPerformanceRoute
  '/app/reviews': typeof AuthenticatedAppReviewsRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/study': typeof AuthenticatedAppStudyRoute
  '/app': typeof AuthenticatedAppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/app/cycle': typeof AuthenticatedAppCycleRoute
  '/_authenticated/app/edital': typeof AuthenticatedAppEditalRoute
  '/_authenticated/app/errors': typeof AuthenticatedAppErrorsRoute
  '/_authenticated/app/flashcards': typeof AuthenticatedAppFlashcardsRoute
  '/_authenticated/app/hours': typeof AuthenticatedAppHoursRoute
  '/_authenticated/app/importance': typeof AuthenticatedAppImportanceRoute
  '/_authenticated/app/pdf-batteries': typeof AuthenticatedAppPdfBatteriesRoute
  '/_authenticated/app/performance': typeof AuthenticatedAppPerformanceRoute
  '/_authenticated/app/reviews': typeof AuthenticatedAppReviewsRoute
  '/_authenticated/app/settings': typeof AuthenticatedAppSettingsRoute
  '/_authenticated/app/study': typeof AuthenticatedAppStudyRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/app/cycle'
    | '/app/edital'
    | '/app/errors'
    | '/app/flashcards'
    | '/app/hours'
    | '/app/importance'
    | '/app/pdf-batteries'
    | '/app/performance'
    | '/app/reviews'
    | '/app/settings'
    | '/app/study'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/cycle'
    | '/app/edital'
    | '/app/errors'
    | '/app/flashcards'
    | '/app/hours'
    | '/app/importance'
    | '/app/pdf-batteries'
    | '/app/performance'
    | '/app/reviews'
    | '/app/settings'
    | '/app/study'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/app/cycle'
    | '/_authenticated/app/edital'
    | '/_authenticated/app/errors'
    | '/_authenticated/app/flashcards'
    | '/_authenticated/app/hours'
    | '/_authenticated/app/importance'
    | '/_authenticated/app/pdf-batteries'
    | '/_authenticated/app/performance'
    | '/_authenticated/app/reviews'
    | '/_authenticated/app/settings'
    | '/_authenticated/app/study'
    | '/_authenticated/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/study': {
      id: '/_authenticated/app/study'
      path: '/app/study'
      fullPath: '/app/study'
      preLoaderRoute: typeof AuthenticatedAppStudyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/settings': {
      id: '/_authenticated/app/settings'
      path: '/app/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/reviews': {
      id: '/_authenticated/app/reviews'
      path: '/app/reviews'
      fullPath: '/app/reviews'
      preLoaderRoute: typeof AuthenticatedAppReviewsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/performance': {
      id: '/_authenticated/app/performance'
      path: '/app/performance'
      fullPath: '/app/performance'
      preLoaderRoute: typeof AuthenticatedAppPerformanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/pdf-batteries': {
      id: '/_authenticated/app/pdf-batteries'
      path: '/app/pdf-batteries'
      fullPath: '/app/pdf-batteries'
      preLoaderRoute: typeof AuthenticatedAppPdfBatteriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/importance': {
      id: '/_authenticated/app/importance'
      path: '/app/importance'
      fullPath: '/app/importance'
      preLoaderRoute: typeof AuthenticatedAppImportanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/hours': {
      id: '/_authenticated/app/hours'
      path: '/app/hours'
      fullPath: '/app/hours'
      preLoaderRoute: typeof AuthenticatedAppHoursRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/flashcards': {
      id: '/_authenticated/app/flashcards'
      path: '/app/flashcards'
      fullPath: '/app/flashcards'
      preLoaderRoute: typeof AuthenticatedAppFlashcardsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/errors': {
      id: '/_authenticated/app/errors'
      path: '/app/errors'
      fullPath: '/app/errors'
      preLoaderRoute: typeof AuthenticatedAppErrorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/edital': {
      id: '/_authenticated/app/edital'
      path: '/app/edital'
      fullPath: '/app/edital'
      preLoaderRoute: typeof AuthenticatedAppEditalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/cycle': {
      id: '/_authenticated/app/cycle'
      path: '/app/cycle'
      fullPath: '/app/cycle'
      preLoaderRoute: typeof AuthenticatedAppCycleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppCycleRoute: typeof AuthenticatedAppCycleRoute
  AuthenticatedAppEditalRoute: typeof AuthenticatedAppEditalRoute
  AuthenticatedAppErrorsRoute: typeof AuthenticatedAppErrorsRoute
  AuthenticatedAppFlashcardsRoute: typeof AuthenticatedAppFlashcardsRoute
  AuthenticatedAppHoursRoute: typeof AuthenticatedAppHoursRoute
  AuthenticatedAppImportanceRoute: typeof AuthenticatedAppImportanceRoute
  AuthenticatedAppPdfBatteriesRoute: typeof AuthenticatedAppPdfBatteriesRoute
  AuthenticatedAppPerformanceRoute: typeof AuthenticatedAppPerformanceRoute
  AuthenticatedAppReviewsRoute: typeof AuthenticatedAppReviewsRoute
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRoute
  AuthenticatedAppStudyRoute: typeof AuthenticatedAppStudyRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppCycleRoute: AuthenticatedAppCycleRoute,
  AuthenticatedAppEditalRoute: AuthenticatedAppEditalRoute,
  AuthenticatedAppErrorsRoute: AuthenticatedAppErrorsRoute,
  AuthenticatedAppFlashcardsRoute: AuthenticatedAppFlashcardsRoute,
  AuthenticatedAppHoursRoute: AuthenticatedAppHoursRoute,
  AuthenticatedAppImportanceRoute: AuthenticatedAppImportanceRoute,
  AuthenticatedAppPdfBatteriesRoute: AuthenticatedAppPdfBatteriesRoute,
  AuthenticatedAppPerformanceRoute: AuthenticatedAppPerformanceRoute,
  AuthenticatedAppReviewsRoute: AuthenticatedAppReviewsRoute,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRoute,
  AuthenticatedAppStudyRoute: AuthenticatedAppStudyRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
