ALTER TABLE public.subjects
  ADD COLUMN IF NOT EXISTS planned_hours_per_week NUMERIC NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS exam_questions INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS min_questions INTEGER NOT NULL DEFAULT 0;

ALTER TABLE public.study_sessions
  ADD COLUMN IF NOT EXISTS task TEXT,
  ADD COLUMN IF NOT EXISTS lesson TEXT,
  ADD COLUMN IF NOT EXISTS page_start INTEGER,
  ADD COLUMN IF NOT EXISTS page_end INTEGER;

ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS review_intervals INTEGER[] NOT NULL DEFAULT '{7,15,30,30,60,60,60,60,60,60}';